"""starting db from scratch

Revision ID: 7a98bee8c645
Revises: 
Create Date: 2021-10-24 20:18:12.362329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a98bee8c645'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_type',
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('account_type_id')
    )
    op.create_index(op.f('ix_account_type_account_type'), 'account_type', ['account_type'], unique=False)
    op.create_table('institution',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('institution_id')
    )
    op.create_index(op.f('ix_institution_institution_name'), 'institution', ['institution_name'], unique=False)
    op.create_table('merchant',
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['account_type.account_type_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_ingested', sa.DateTime(), nullable=True),
    sa.Column('date_transaction', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transaction_date_ingested'), 'transaction', ['date_ingested'], unique=False)
    op.create_index(op.f('ix_transaction_date_transaction'), 'transaction', ['date_transaction'], unique=False)
    op.create_table('transaction_tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_tag')
    op.drop_index(op.f('ix_transaction_date_transaction'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date_ingested'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('merchant')
    op.drop_index(op.f('ix_institution_institution_name'), table_name='institution')
    op.drop_table('institution')
    op.drop_index(op.f('ix_account_type_account_type'), table_name='account_type')
    op.drop_table('account_type')
    # ### end Alembic commands ###
