"""changing to just id, not user_id

Revision ID: dd91f1f764f7
Revises: c1507f1fc8ce
Create Date: 2022-06-05 10:56:58.950678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd91f1f764f7'
down_revision = 'c1507f1fc8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_column('user', 'id')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
